### 
### Generating lists of numbers
### 

require '~/voice/my_commands/generators/list_generator'


def spoken_number(number)
  irregular = %W[zero one two three four five six seven eight nine ten
                 eleven twelve thirteen fourteen fifteen sixteen seventeen
                 eighteen nineteen]

  tens = %W[twenty thirty forty fifty sixty seventy eighty ninety]

  if 0<=number and number<irregular.length then
    return irregular[number]
  elsif 20<=number && number<100 && (number%10==0) then
    return tens[number/10-2]
  elsif 20<=number && number<100 then
    #return tens[number/10-2]+"-"+irregular[number%10]
    return tens[number/10-2]+" "+irregular[number%10]
  elsif number==100 then
    return "one hundred"
  else
    return number.to_s
  end
end



def number_list(start, stop)
  # use both forms for these:
  #exceptions = [ 61, 81 ]
  exceptions = []

  entries = []
  start.upto(stop) do |i|
    #entries << [i.to_s, i.to_s]; next
    entries << [spoken_number(i), i.to_s]
    if exceptions.include?(i) then
      entries << [i.to_s, i.to_s]
    end
  end

  list = TrivialList.new(entries)
  list.sort_by_written = true
  list
end

def print_number_list(name, start, stop)
  puts number_list(start, stop).generate(name)
end



puts <<HEADER
###
### Custom number lists to deal with recognizer problems
###
### WARNING: this file is automatically generated by numbers.rb!
###

  # recognition of numbers may be improved using their written-out forms:
# $set numbers "zero,one,two,three,four,five,six,seven,eight,nine,ten,eleven,twelve,thirteen,fourteen,fifteen,sixteen,seventeen,eighteen,nineteen,twenty,twenty-one,twenty-two,twenty-three,twenty-four,twenty-five,twenty-six,twenty-seven,twenty-eight,twenty-nine,thirty,thirty-one,thirty-two,thirty-three,thirty-four,thirty-five,thirty-six,thirty-seven,thirty-eight,thirty-nine,forty,forty-one,forty-two,forty-three,forty-four,forty-five,forty-six,forty-seven,forty-eight,forty-nine,fifty,fifty-one,fifty-two,fifty-three,fifty-four,fifty-five,fifty-six,fifty-seven,fifty-eight,fifty-nine,sixty,sixty-one,sixty-two,sixty-three,sixty-four,sixty-five,sixty-six,sixty-seven,sixty-eight,sixty-nine,seventy,seventy-one,seventy-two,seventy-three,seventy-four,seventy-five,seventy-six,seventy-seven,seventy-eight,seventy-nine,eighty,eighty-one,eighty-two,eighty-three,eighty-four,eighty-five,eighty-six,eighty-seven,eighty-eight,eighty-nine,ninety,ninety-one,ninety-two,ninety-three,ninety-four,ninety-five,ninety-six,ninety-seven,ninety-eight,ninety-nine";


HEADER


print_number_list("my0to99", 0, 99)
puts
print_number_list("r", 0, 99)
puts
print_number_list("my1to100", 1, 100)
