## 
## Locations of C header files for symbol extraction
## 

# header files for C standard library for symbol extraction:
CLIB= \
    /usr/include/assert.h \
    /usr/include/complex.h \
    /usr/include/ctype.h \
    /usr/include/errno.h \
      /usr/include/asm-generic/errno.h \
      /usr/include/asm-generic/errno-base.h \
    /usr/include/fenv.h \
    /usr/include/float.h \
    /usr/include/inttypes.h \
    /usr/include/iso646.h \
    /usr/include/limits.h \
    /usr/include/locale.h \
    /usr/include/math.h \
    /usr/include/setjmp.h \
    /usr/include/signal.h \
    /usr/include/stdalign.h \
    /usr/include/stdarg.h \
    /usr/include/stdatomic.h \
    /usr/include/stdbool.h \
    /usr/include/stddef.h \
    /usr/include/stdint.h \
    /usr/include/stdio.h \
    /usr/include/stdlib.h \
    /usr/include/stdnoreturn.h \
    /usr/include/string.h \
    /usr/include/tgmath.h \
    /usr/include/threads.h \
    /usr/include/time.h \
    /usr/include/uchar.h \
    /usr/include/wchar.h \
    /usr/include/wctype.h

# header files for usual Unix/Linux system calls for symbol extraction:
UNIX= \
    /usr/include/dirent.h \
    /usr/include/fcntl.h \
      /usr/include/bits/fcntl.h \
    /usr/include/sys/file.h \
    /usr/include/sys/mman.h \
    /usr/include/sys/socket.h \
    /usr/include/sys/stat.h \
    /usr/include/sys/types.h \
    /usr/include/unistd.h 

PTHREADS= \
    /usr/include/pthread.h



## 
## 
## 

-include Makefile.local


clean::
	rm -f symbols.txt BROWSE
